# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - .build

# Opt-in rules you want beyond defaults
opt_in_rules:
  - empty_count
  - explicit_init

# Adjust specific rule settings
line_length: 130
